### PR TITLE
Create calculate_complexity_score.py

### PR DESCRIPTION
**Pull request by jguillen15**
First attempt to create SBOL utility to calculate complexity score of a sequence

### CODE REVIEW

**Comment by isaacguerreir** [comment]
@jakebeal suggested using provenance and measure objects to record the complexity score information of the list of sequences.

**Comment by jakebeal** [comment]
In addition to modifying the SBOL objects, the function might also want to return a simple dictionary of results {object,score}, to be easily at hand for interpretation by a caller.

**Review by jakebeal — COMMENTED** [review]
This looks good enough to me to bring in. I will make a few clean-up modifications and then will approve and merge.

**Comment by jguillen15** [comment]
Great! :D
Before doing the merge, don´t I need first to restore the sbol_diff.py file in the pull request?
Thanks

**Comment by jakebeal** [comment]
That is one of the clean-ups that I will do.

**Review by jakebeal — APPROVED** [review]
Merging into a temp branch for clean-up before bringing into develop

**Comment by jakebeal** [comment]
I am going to merge this into my working branch despite the test failures, because I need to be able to fix the issues on a branch that I can push to.

**Pull request merged**
